#!/bin/bash

# purpose of this script:
#  Take a given URL, call the URL,
#  and depending on the details of the http-answer return a status to nagios.
#
#  note:
#  - Does not check https certificate.
#  - Measures roundtrip time in seconds (which is quite rough, to be honest).
#  - An acceptable HTTP status code is matched just with: the word OK follows somewhere after HTTP/.

first(){ # first function called
    EXIT=3; ERRORS="" ; NOTES=""; STATS="" # start with these defaults
    options "$@"
    call_url
    analyze_response
    answer_nagios
}

call_url(){ # send http request to easydb5
    TIMESTART=`date +%s`
    RESPONSE=`wget "$URL" -t 1 -S -q --no-cache --no-check-certificate -O - 2>&1`
    TIMESTOP=`date +%s`
}

analyze_response(){ # process answer from easydb5

    # analyze response duration
    TIME_TAKEN=$(($TIMESTOP-$TIMESTART))
    STATS="${STATS} Roundtrip=$TIME_TAKEN"
    if [ $TIME_TAKEN -lt $WARN_TIMEOUT ] ; then
        EXIT=0; NOTES="$NOTES easydb responded faster than $WARN_TIMEOUT seconds."
    elif [ $TIME_TAKEN -lt $CRIT_TIMEOUT ] ; then
        EXIT=1; ERRORS="$ERRORS easydb responded slower that $WARN_TIMEOUT seconds."
    else
        EXIT=2; ERRORS="$ERRORS easydb did not respond in $CRIT_TIMEOUT seconds."
    fi

    # analyze http-status
    # look on all lines except the paragraph that starts with { and ends with }, each on their own lines.
    HEADERS=`echo "$RESPONSE"|sed '/^[[:space:]]*{[[:space:]]*$/,/^[[:space:]]*}[[:space:]]*$/d'`
    HTTP_STATUS_LINE=`echo "$HEADERS"|grep '^[[:space:]]*HTTP/'`
    HTTP_STATUS_LINE=`echo $HTTP_STATUS_LINE`          # removes line breaks. Line breaks in icinga web UI are cut off in some places and look broken.
    if echo "$HTTP_STATUS_LINE" | grep -qw 'OK'; then
        NOTES="$NOTES STATUS OK: ${HTTP_STATUS_LINE}."
    else
        EXIT=2
        ERRORS="$ERRORS STATUS: ${HTTP_STATUS_LINE}!"
    fi

    # analyze response content
    # only look on the paragraph that starts with { and ends with }, each on their own lines.
    CONTENT=`echo "$RESPONSE"|sed -n '/^[[:space:]]*{[[:space:]]*$/,/^[[:space:]]*}[[:space:]]*$/p'`
    # is $SEARCH_STRING in there?!
    if echo "$CONTENT" | grep -q "$SEARCH_STRING"; then
        NOTES="$NOTES Found $SEARCH_STRING in answer."
    else
        EXIT=2
        ERRORS="$ERRORS Did not find $SEARCH_STRING in answer!"
    fi

    # a typical response:
     
    #  HTTP/1.1 200 OK
    #  Date: Sun, 31 Dec 2017, 23:59:59 GMT
    #  Server: nginx/1.6.2
    #  Content-Type: application/json; charset=utf-8
    #  Vary: Accept-Encoding,Origin
    #  Cache-Control: no-cache
    #  Last-Modified: Sun, 31 Dec 2017, 23:59:59 GMT
    #  X-Easydb-API-Version: 1
    #  X-Easydb-User-Schema-Version: 42
    #  Pragma: no-cache
    #  X-Easydb-Solution: base
    #  X-Easydb-Base-Schema-Version: 179
    #  Keep-Alive: timeout=5, max=100
    #  Connection: Keep-Alive
    #  Transfer-Encoding: chunked
    #{
    #    "name": "ffffffff-ffff-ffff-ffff-ffffffffffff",
    #    "api": 1,
    #    "server_version": 1,
    #    "user-schema": 99,
    #    "solution": "base",
    #    "db-name": "easy5-uni-atlantis",
    #    "startup_time": "2017-01-31T01:59:59Z",
    #    "external_eas_url": "http://easydb.uni-atlantis.de/eas",
    #    "server_time": "2017-12-31T23:59:59Z"
    #}
}

options(){ # process command line parameters
    URL="$1"
    [ -z "$URL" ] && ERRORS="URL missing as first argument" EXIT=3 answer_nagios
    shift

    # defaults:
    WARN_TIMEOUT=5
    CRIT_TIMEOUT=30
    SEARCH_STRING=db-name

    while [ "$1" ] ; do
        case "$1" in
        -w)
            WARN_TIMEOUT=$2;shift
        ;;
        -c)
            CRIT_TIMEOUT=$2;shift
        ;;
        -s)
            SEARCH_STRING="$2";shift
        ;;
        *)
            ERRORS="unknown argument '$1'" EXIT=3 answer_nagios
        esac
        shift
    done
}

answer_nagios(){ # follow nagios rules for text syntax and return/exit code/status/value
    case $EXIT in
    0) echo -n "OK-" ;;
    1) echo -n "WARNING-" ;;
    2) echo -n "CRITICAL-" ;;
    3) echo -n "UNKNOWN-" ;;
    esac
    echo "$ERRORS$NOTES"'| '"$STATS"
    exit $EXIT
}

first "$@"
